 CREATETABLE "SYSTEM"."STUDENTBIODATA"
 (
 "NAME" VARCHAR2(255 BYTE),
 "ROLLNUMBER"VARCHAR2(20BYTE),
 "FATHERNAME"VARCHAR2(255BYTE),
 "MOTHERNAME"VARCHAR2(255BYTE),
 "DATEOFBIRTH" DATE,
 "GENDER" VARCHAR2(10 BYTE),
 "EMAIL" VARCHAR2(255 BYTE),
"BRANCH" VARCHAR2(100 BYTE),
 "ATTENDANCEPERCENTAGE"NUMBER(*,0),
 "CGPA" NUMBER(*,0),
 "COURSEDURATION" VARCHAR2(30BYTE),
 "ADDRESS" VARCHAR2(255 BYTE),
 "PHOTO" BLOB,
 PRIMARYKEY("ROLLNUMBER")
 );
 